# Generated by Django 5.0.2 on 2024-02-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
